### ISSUE TITLE
New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.

### ISSUE THREAD

**Issue by PeterSDFSDF** [AsBuiltReport/AsBuiltReport.DellEMC.VxRail#2]
New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
+ New-AsBuiltReport -Report DellEMC.VxRail -Target 'vcenter...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

Command:
New-AsBuiltReport -Report DellEMC.VxRail -Target 'vcenter' -Username 'username' -Password 'password' -Format Html,Word -OutputFolderPath 'C:\Users\username\Documents' -Verbose

What i get:

VERBOSE: As Built Report configuration file not saved.
VERBOSE: Config.Report.Author = User
VERBOSE: Config.UserFolder.Path = C:\Users\USER\AsBuiltReport
VERBOSE: Config.Company.FullName =
VERBOSE: Config.Company.Contact =
VERBOSE: Config.Company.Phone =
VERBOSE: Config.Company.Email =
VERBOSE: Config.Company.ShortName =
VERBOSE: Config.Company.Address =
VERBOSE: Config.Email.Port =
VERBOSE: Config.Email.Credentials =
VERBOSE: Config.Email.Server =
VERBOSE: Config.Email.To =
VERBOSE: Config.Email.From =
VERBOSE: Config.Email.UseSSL =
VERBOSE: Config.Email.Body =
VERBOSE: Loading module from path
'C:\Users\USER\Documents\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRa
il.psm1'.
VERBOSE: Loading report configuration file from path
'C:\Users\USER\Documents\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRa
il.json'.
VERBOSE: Setting report filename to 'Dell EMC VxRail As Built Report'.
VERBOSE: [ 19:18:37:819 ] [ Document ] - Document 'Dell EMC VxRail As Built Report' processing started.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Executing report style script from path
'C:\Users\USER\Documents\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRa
il.Style.ps1'.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Setting global document options.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Enabling section/heading numbering.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Setting default font(s) to 'Arial'.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Setting page top margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page right margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page bottom margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page left margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page size to 'A4'.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page orientation to 'Portrait'.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page height to '297'mm.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting page width to '210'mm.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Title'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Title2'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Title3'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Heading1'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Heading2'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Heading3'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Heading4'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Heading5'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Normal'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'Caption'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'Header'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'Footer'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'TOC'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'TableDefaultHeading'.
VERBOSE: [ 19:18:37:976 ] [ Document ] - Setting document style 'TableDefaultRow'.
VERBOSE: [ 19:18:37:976 ] [ Document ] - Setting document style 'Critical'.
VERBOSE: [ 19:18:37:976 ] [ Document ] - Setting document style 'Warning'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting document style 'Info'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting document style 'OK'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting table style 'TableDefault'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting table style 'Borderless'.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing document header started.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing paragraph 'Dell EMC VxRail As Built Report - v1.0'.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing document header completed.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing document footer started.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing paragraph 'Page <!# PageNumber #!>'.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing document footer completed.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing blank line.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing paragraph 'Dell EMC VxRail As Built Report'.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing blank line.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing table 'Cover Page'.
VERBOSE: [ 19:18:38:038 ] [ Document ] - Processing page break.
VERBOSE: [ 19:18:38:038 ] [ Document ] - Processing table of contents 'Table of Contents'.
VERBOSE: [ 19:18:38:038 ] [ Document ] - Processing page break.
VERBOSE: [ 19:18:38:069 ] [ Document ] - Connecting to vCenter Server
VERBOSE: [ 19:18:39:522 ] [ Document ] - Collecting VxRail Manager Information
VERBOSE: [ 19:18:39:726 ] [ Document ] - Performing API reference calls
New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
+ New-AsBuiltReport -Report DellEMC.VxRail -Target 'vcenter ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltRepo

**Comment by tpcarman** [comment]
Could you please provide more information as to the VxRail, vCenter & PowerCLI versions you are using?

**Comment by PeterSDFSDF** [comment]
fyi New-AsBuiltReportConfig -Report VMware.vSphere ... works

VxRail 4.7.526

External vCenter 6.7 build 17137327

PowerCLI Version
----------------
   VMware PowerCLI 12.1.0 build 17009493
---------------
Component Versions
---------------
   VMware Common PowerCLI Component 12.1 build 16997174
   VMware Cis Core PowerCLI Component PowerCLI Component 12.1 build 16997582
   VMware VimAutomation VICore Commands PowerCLI Component PowerCLI Component 12.1 build 16997984
   VMware VimAutomation Storage PowerCLI Component PowerCLI Component 12.1 build 17001270
   VMware VimAutomation Vds Commands PowerCLI Component PowerCLI Component 12.1 build 17001377
   VMware vSphere Update Manager PowerCLI 6.5 build 16941488

A  vsphere.local user with permissons: 
Global
-Licenses
-Settings
Host
-CIM
-CIM interaction
Configuration
-Change settings
-Profile-driven storage
-Profile-driven storage view
VMware vSphere Update Manager
-Manage Patches and Upgrades
-View Compliance Status
VxRail
-View VxRail clusters

**Comment by tpcarman** [comment]
Are you able to run the VxRail report using full administrator (administrator@vsphere.local) privileges?

When you run the VMware vSphere report, does it report the name of VxRail Manager in the vCenter section (Using InfoLevel 3 or above)?

**Comment by PeterSDFSDF** [comment]
I do not run the report as admin .. the user has the permissions i listed. 
Only has permissons for the VXrail cluster. 
The VM is listed:
VxRail Manager | On | IP-1111-1-11- | 2 | 8 | 168.08 | 27.48 | v11 | OK

**Comment by PeterSDFSDF** [comment]
I'm not seeing any vxrail related config with the user if i login to vCenter and go to cluster/configure or cluster/monitor so some permisson problems... Testing some stuff.

**Comment by tpcarman** [comment]
Does the VMware vSphere report show the VxRail Manager Server as shown here? Note, you will need to configure the vCenter InfoLevel within the report JSON config to 3 or above.
![image](https://user-images.githubusercontent.com/15333667/106816522-9ccbe580-66c9-11eb-800d-02ae8ea7a0a4.png)

**Comment by PeterSDFSDF** [comment]
Yes

![image](https://user-images.githubusercontent.com/78501644/106816940-6e70ea80-6676-11eb-9aa3-69956ec9165a.png)

**Comment by tpcarman** [comment]
OK, then I'm guessing it's an issue with the user account you are using. You will need to test with an admin account and work back from there. Unfortunately I no longer have access to a VxRail environment to test this any further.

**Comment by tpcarman** [comment]
@PeterSDFSDF were you able to successfully run the report with administrator privileges?

**Comment by vishnuc85** [comment]
Hello I have the same problem with administrator@vsphere.local. Running the VxRail Version: 4.7.527-26902834


New-AsBuiltReport -Report DellEMC.VxRail -Target 'vcenter' -Username 'username' -Password 'password' -Format Html,Word -OutputFolderPath 'C:\Users\username\Documents' -Verbose

What i get:

VERBOSE: As Built Report configuration file not saved.
VERBOSE: Config.Report.Author = User
VERBOSE: Config.UserFolder.Path = C:\Users\USER\AsBuiltReport
VERBOSE: Config.Company.FullName =
VERBOSE: Config.Company.Contact =
VERBOSE: Config.Company.Phone =
VERBOSE: Config.Company.Email =
VERBOSE: Config.Company.ShortName =
VERBOSE: Config.Company.Address =
VERBOSE: Config.Email.Port =
VERBOSE: Config.Email.Credentials =
VERBOSE: Config.Email.Server =
VERBOSE: Config.Email.To =
VERBOSE: Config.Email.From =
VERBOSE: Config.Email.UseSSL =
VERBOSE: Config.Email.Body =
VERBOSE: Loading module from path
'C:\Users\USER\Documents\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRa
il.psm1'.
VERBOSE: Loading report configuration file from path
'C:\Users\USER\Documents\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRa
il.json'.
VERBOSE: Setting report filename to 'Dell EMC VxRail As Built Report'.
VERBOSE: [ 19:18:37:819 ] [ Document ] - Document 'Dell EMC VxRail As Built Report' processing started.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Executing report style script from path
'C:\Users\USER\Documents\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRa
il.Style.ps1'.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Setting global document options.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Enabling section/heading numbering.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Setting default font(s) to 'Arial'.
VERBOSE: [ 19:18:37:897 ] [ Document ] - Setting page top margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page right margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page bottom margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page left margin to '25,05'mm.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page size to 'A4'.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page orientation to 'Portrait'.
VERBOSE: [ 19:18:37:913 ] [ Document ] - Setting page height to '297'mm.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting page width to '210'mm.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Title'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Title2'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Title3'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Heading1'.
VERBOSE: [ 19:18:37:929 ] [ Document ] - Setting document style 'Heading2'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Heading3'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Heading4'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Heading5'.
VERBOSE: [ 19:18:37:944 ] [ Document ] - Setting document style 'Normal'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'Caption'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'Header'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'Footer'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'TOC'.
VERBOSE: [ 19:18:37:960 ] [ Document ] - Setting document style 'TableDefaultHeading'.
VERBOSE: [ 19:18:37:976 ] [ Document ] - Setting document style 'TableDefaultRow'.
VERBOSE: [ 19:18:37:976 ] [ Document ] - Setting document style 'Critical'.
VERBOSE: [ 19:18:37:976 ] [ Document ] - Setting document style 'Warning'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting document style 'Info'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting document style 'OK'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting table style 'TableDefault'.
VERBOSE: [ 19:18:37:991 ] [ Document ] - Setting table style 'Borderless'.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing document header started.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing paragraph 'Dell EMC VxRail As Built Report - v1.0'.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing document header completed.
VERBOSE: [ 19:18:38:007 ] [ Document ] - Processing document footer started.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing paragraph 'Page <!# PageNumber #!>'.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing document footer completed.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing blank line.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing paragraph 'Dell EMC VxRail As Built Report'.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing blank line.
VERBOSE: [ 19:18:38:022 ] [ Document ] - Processing table 'Cover Page'.
VERBOSE: [ 19:18:38:038 ] [ Document ] - Processing page break.
VERBOSE: [ 19:18:38:038 ] [ Document ] - Processing table of contents 'Table of Contents'.
VERBOSE: [ 19:18:38:038 ] [ Document ] - Processing page break.
VERBOSE: [ 19:18:38:069 ] [ Document ] - Connecting to vCenter Server
VERBOSE: [ 19:18:39:522 ] [ Document ] - Collecting VxRail Manager Information
VERBOSE: [ 19:18:39:726 ] [ Document ] - Performing API reference calls
New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1

New-AsBuiltReport -Report DellEMC.VxRail -Target 'vcenter ...
  + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltRepo

**Comment by tpcarman** [comment]
Hi @vishnuc85,
Would you mind trying the latest [commit](https://github.com/AsBuiltReport/AsBuiltReport.DellEMC.VxRail/commit/0ec3d9c5f8a6e562f73b69cf9fb36cce6167023b) and let me know if this resolves your issue.
Thanks.

**Comment by vishnuc85** [comment]
Hello Its same,

Please see below


New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
+ New-AsBuiltReport -Report DellEMC.VxRail -Target '192.33.30.200' -User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by vishnuc85** [comment]
Would you like to save the As Built Report configuration file? (y/n): y
Enter a name for the As Built Report configuration file [AsBuiltReport]:
Enter the path to save the As Built Report configuration file [C:\Users\Administrator\AsBuiltReport]:
VERBOSE: Saving As Built Report configuration file 'AsBuiltReport.json' to path 'C:\Users\Administrator\AsBuiltReport'.
VERBOSE: Config.Report.Author = Administrator
VERBOSE: Config.UserFolder.Path = C:\Users\Administrator\AsBuiltReport
VERBOSE: Config.Company.FullName =
VERBOSE: Config.Company.Contact =
VERBOSE: Config.Company.Phone =
VERBOSE: Config.Company.Email =
VERBOSE: Config.Company.ShortName =
VERBOSE: Config.Company.Address =
VERBOSE: Config.Email.Port =
VERBOSE: Config.Email.Credentials =
VERBOSE: Config.Email.Server =
VERBOSE: Config.Email.To =
VERBOSE: Config.Email.From =
VERBOSE: Config.Email.UseSSL =
VERBOSE: Config.Email.Body =
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRail.psm1'.
VERBOSE: Loading module from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRail.psm1'.
VERBOSE: Loading report configuration file from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRail.json'.
VERBOSE: Setting report filename to 'PBL'.
VERBOSE: [ 14:34:02:677 ] [ Document ] - Document 'xx' processing started.
VERBOSE: [ 14:34:02:692 ] [ Document ] - Executing report style script from path 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\AsBuiltReport.DellEMC.VxRail\AsBuiltReport.DellEMC.VxRail.Style.ps1'.
VERBOSE: [ 14:34:02:724 ] [ Document ] - Setting global document options.
VERBOSE: [ 14:34:02:724 ] [ Document ] - Enabling section/heading numbering.
VERBOSE: [ 14:34:02:724 ] [ Document ] - Setting default font(s) to 'Arial'.
VERBOSE: [ 14:34:02:724 ] [ Document ] - Setting page top margin to '25.05'mm.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page right margin to '25.05'mm.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page bottom margin to '25.05'mm.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page left margin to '25.05'mm.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page size to 'A4'.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page orientation to 'Portrait'.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page height to '297'mm.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting page width to '210'mm.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting document style 'Title'.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting document style 'Title2'.
VERBOSE: [ 14:34:02:739 ] [ Document ] - Setting document style 'Title3'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Heading1'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Heading2'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Heading3'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Heading4'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Heading5'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Normal'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Caption'.
VERBOSE: [ 14:34:02:755 ] [ Document ] - Setting document style 'Header'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'Footer'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'TOC'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'TableDefaultHeading'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'TableDefaultRow'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'Critical'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'Warning'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'Info'.
VERBOSE: [ 14:34:02:770 ] [ Document ] - Setting document style 'OK'.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Setting table style 'TableDefault'.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Setting table style 'Borderless'.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Processing document header started.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Processing paragraph 'PBL - v1.0'.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Processing document header completed.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Processing document footer started.
VERBOSE: [ 14:34:02:786 ] [ Document ] - Processing paragraph 'Page <!# PageNumber #!>'.
VERBOSE: [ 14:34:02:802 ] [ Document ] - Processing document footer completed.
VERBOSE: [ 14:34:02:802 ] [ Document ] - Processing blank line.
VERBOSE: [ 14:34:02:802 ] [ Document ] - Processing paragraph 'PBL'.
VERBOSE: [ 14:34:02:817 ] [ Document ] - Processing blank line.
VERBOSE: [ 14:34:02:817 ] [ Document ] - Processing table 'Cover Page'.
VERBOSE: [ 14:34:02:817 ] [ Document ] - Processing page break.
VERBOSE: [ 14:34:02:817 ] [ Document ] - Processing table of contents 'Table of Contents'.
VERBOSE: [ 14:34:02:817 ] [ Document ] - Processing page break.
VERBOSE: [ 14:34:02:833 ] [ Document ] - Connecting to vCenter Server 'xx.xx.xxx.com'.
VERBOSE: [ 14:34:03:818 ] [ Document ] - Collecting VxRail Manager Information
VERBOSE: [ 14:34:03:897 ] [ Document ] - Performing API reference calls
New-AsBuiltReport : Cannot bind argument to parameter 'Name' because it is an empty string.
At line:1 char:1
+ New-AsBuiltReport -Report DellEMC.VxRail -Target 'xxx.xx.xx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

**Comment by tpcarman** [comment]
@vishnuc85 I have added some more verbose logging in the lastest [commit](https://github.com/AsBuiltReport/AsBuiltReport.DellEMC.VxRail/commit/0eff7a6c01a1045576120399c9b57f8ebc336156). Can you please try this?

**Comment by tpcarman** [comment]
Please try [v0.3.0](https://github.com/AsBuiltReport/AsBuiltReport.DellEMC.VxRail/releases/tag/v0.3.0), if the issue still occurs, please reopen this issue.
